<a href="https://colab.research.google.com/github/vamseerd/ML_Test/blob/test1/Housing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt

a = tf.constant(1, name='a_var')
b = tf.constant(2, name='b_bar')
c = tf.Variable(a + b)

init = tf.global_variables_initializer()
with tf.Session() as session:                    
    session.run(init)                            
    print(session.run(a))
    print(session.run(b))
    print(session.run(c))



1
2
3
[-10.          -5.55555556  -1.11111111   3.33333333   7.77777778
  12.22222222  16.66666667  21.11111111  25.55555556  30.        ]
[ 200.         41.975304  -76.54321  -155.55554  -195.06174  -195.06174
 -155.55554   -76.54324    41.97534   200.      ]


In [20]:
x = tf.placeholder(dtype=tf.float32)
a = tf.constant(1, dtype=tf.float32)
b = tf.constant(-20, dtype=tf.float32)
c = tf.constant(-100, dtype=tf.float32)

y = a * (x ** 2) + b * x + c

x_feed = np.linspace(-10, 30, num=10)

init = tf.global_variables_initializer()
with tf.Session() as session:                    
    session.run(init)     
    print(session.run(a))
    print(session.run(b))
    print(session.run(c))
print(x_feed)

with tf.Session() as sess:
  results = sess.run(y, feed_dict={x: x_feed})
print(results)

Tensor("Const_15:0", shape=(), dtype=float32)
Tensor("Const_16:0", shape=(), dtype=float32)
Tensor("Const_17:0", shape=(), dtype=float32)
1.0
-20.0
-100.0
[-10.          -5.55555556  -1.11111111   3.33333333   7.77777778
  12.22222222  16.66666667  21.11111111  25.55555556  30.        ]
[ 200.         41.975304  -76.54321  -155.55554  -195.06174  -195.06174
 -155.55554   -76.54324    41.97534   200.      ]


In [50]:
import tensorflow as tf

x = tf.placeholder(dtype=tf.float32, shape=(None, 1))
y_true = tf.placeholder(dtype=tf.float32, shape=(None, 1))

l = tf.Variable(2, name='l', dtype=tf.float32)
log_l = tf.log(l)
loss = tf.square(log_l)

linear_model = tf.layers.Dense(
                   units=1, 
                   bias_initializer=tf.constant_initializer(1))
y_pred = linear_model(x)

optimizer = tf.train.GradientDescentOptimizer(0.01)
train = optimizer.minimize(loss)

init = tf.global_variables_initializer()

x_values = np.array([[1], [2], [3], [4]])
y_values = np.array([[0], [-1], [-2], [-3]])

with tf.Session() as sess:
  sess.run(init)
  for i in range(10):
    _, loss_value = sess.run((train, loss),
                             feed_dict={x: x_values, y_true: y_values})
    weights = sess.run(linear_model.weights)
    bias = sess.run(linear_model.bias)
    preds = sess.run(y_pred, 
                 feed_dict={x: x_values})
    print(preds)


[[1.4991955]
 [1.9983909]
 [2.4975863]
 [2.9967818]]
[[1.4991955]
 [1.9983909]
 [2.4975863]
 [2.9967818]]
[[1.4991955]
 [1.9983909]
 [2.4975863]
 [2.9967818]]
[[1.4991955]
 [1.9983909]
 [2.4975863]
 [2.9967818]]
[[1.4991955]
 [1.9983909]
 [2.4975863]
 [2.9967818]]
[[1.4991955]
 [1.9983909]
 [2.4975863]
 [2.9967818]]
[[1.4991955]
 [1.9983909]
 [2.4975863]
 [2.9967818]]
[[1.4991955]
 [1.9983909]
 [2.4975863]
 [2.9967818]]
[[1.4991955]
 [1.9983909]
 [2.4975863]
 [2.9967818]]
[[1.4991955]
 [1.9983909]
 [2.4975863]
 [2.9967818]]


In [65]:
import tensorflow as tf

x = tf.placeholder(dtype=tf.float32, shape=(None, 1))
y_true = tf.placeholder(dtype=tf.float32, shape=(None, 1))


linear_model = tf.layers.Dense(
                   units=1, 
                   bias_initializer=tf.constant_initializer(1))
y_pred = linear_model(x)

optimizer = tf.train.GradientDescentOptimizer(0.01)
train = optimizer.minimize(loss)

init = tf.global_variables_initializer()

x_values = np.array([[1], [2], [3], [4]])
y_values = np.array([[0], [-1], [-2], [-3]])

with tf.Session() as sess:
  sess.run(init)
  for i in range(1000):
    _, loss_value = sess.run((train, loss),
                             feed_dict={x: x_values, y_true: y_values})
    weights = sess.run(linear_model.weights)
    bias = sess.run(linear_model.bias)
    preds = sess.run(y_pred, 
                 feed_dict={x: x_values})
    print(preds)


[[1.5825053]
 [2.1650107]
 [2.7475162]
 [3.3300214]]
[[1.5825053]
 [2.1650107]
 [2.7475162]
 [3.3300214]]
[[1.5825053]
 [2.1650107]
 [2.7475162]
 [3.3300214]]
[[1.5825053]
 [2.1650107]
 [2.7475162]
 [3.3300214]]
[[1.5825053]
 [2.1650107]
 [2.7475162]
 [3.3300214]]
[[1.5825053]
 [2.1650107]
 [2.7475162]
 [3.3300214]]
[[1.5825053]
 [2.1650107]
 [2.7475162]
 [3.3300214]]
[[1.5825053]
 [2.1650107]
 [2.7475162]
 [3.3300214]]
[[1.5825053]
 [2.1650107]
 [2.7475162]
 [3.3300214]]
[[1.5825053]
 [2.1650107]
 [2.7475162]
 [3.3300214]]
[[1.5825053]
 [2.1650107]
 [2.7475162]
 [3.3300214]]
[[1.5825053]
 [2.1650107]
 [2.7475162]
 [3.3300214]]
[[1.5825053]
 [2.1650107]
 [2.7475162]
 [3.3300214]]
[[1.5825053]
 [2.1650107]
 [2.7475162]
 [3.3300214]]
[[1.5825053]
 [2.1650107]
 [2.7475162]
 [3.3300214]]
[[1.5825053]
 [2.1650107]
 [2.7475162]
 [3.3300214]]
[[1.5825053]
 [2.1650107]
 [2.7475162]
 [3.3300214]]
[[1.5825053]
 [2.1650107]
 [2.7475162]
 [3.3300214]]
[[1.5825053]
 [2.1650107]
 [2.7475162]
 [3.330

In [40]:
import tensorflow as tf

x = tf.Variable(2, name='x', dtype=tf.float32)
log_x = tf.log(x)
log_x_squared = tf.square(log_x)

optimizer = tf.train.GradientDescentOptimizer(0.5)
train = optimizer.minimize(log_x_squared)

init = tf.global_variables_initializer()

with tf.Session() as session:
    session.run(init)
    print("starting at", "x:", session.run(x), "log(x)^2:", session.run(log_x_squared))
    for step in range(10):  
      session.run(train)
      print("step", step, "x:", session.run(x), "log(x)^2:", session.run(log_x_squared))

starting at x: 2.0 log(x)^2: 0.480453
step 0 x: 1.6534264 log(x)^2: 0.25285786
step 1 x: 1.3493005 log(x)^2: 0.08975195
step 2 x: 1.1272697 log(x)^2: 0.014351694
step 3 x: 1.0209966 log(x)^2: 0.0004317743
step 4 x: 1.0006447 log(x)^2: 4.1534943e-07
step 5 x: 1.0000006 log(x)^2: 3.5527118e-13
step 6 x: 1.0 log(x)^2: 0.0
step 7 x: 1.0 log(x)^2: 0.0
step 8 x: 1.0 log(x)^2: 0.0
step 9 x: 1.0 log(x)^2: 0.0
